server:
  port: 11000
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  messages:
    basename: "classpath:i18n/messages"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
    banner: false

logging:
  file:
    name: "logs/${spring.application.name}.log"
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 15
      total-size-cap: 1GB

springdoc:
  api-docs:
    path: "/api-docs"
#  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "health"